### PR TITLE
Improve certificate handling

### PR DESCRIPTION
**Pull request by zyv**

### CODE REVIEW

**Comment by zyv** [comment]
@steinke just sent a clarification per email at support@.

**Comment by zyv** [comment]
@javaes any feedback so far?

**Comment by berend** [comment]
We upgraded to SHA256 hashing, also we don't need the two fingerprint as of now, because that was only for the certificate transition.

**Comment by zyv** [comment]
I'm not sure what is the reasoning behind refusing to add staging & sandbox certificates to the trust manager and forcing us to feed their fingerprints via an environment variable.

This is problematic if one uses figo SDK inside a portal running in an application server started via system service manager. I guess we'll have to use the undocumented `FigoTrustManager.addTrustedFingerprint` hack mentioned in #32 then...

**Comment by berend** [comment]
we will make the handling for other systems better. The reason behind refusing is more, that adding SHA1 hashes is not supported, because we switched to SHA256 hashing. 

So, you are saying that use ENV variables is not possible in your server setup? That is some good information, we will think about other different ways to make that fingerprint configurable.

Thank you.

**Comment by zyv** [comment]
@berend 

> The reason behind refusing is more, that adding SHA1 hashes is not supported, because we switched to SHA256 hashing.

Sorry, but I'm confused now; so how does this preclude you from adding SHA2 fingerprints for `staging` & `sandbox`? The reason why I've submitted SHA1 hashes in my pull request is that it was filed before you decided to move to SHA2. Should I make another pull request?

> So, you are saying that use ENV variables is not possible in your server setup?

It is not entierely impossible, but it is highly problematic. Environment variables are fine if one is working on a program launched via command line, or even a stand-alone service (but already there it's getting annoying). However, passing configuration as environment variables to applications running inside an application container is very difficult. Such applications are usually configured via properties files.

If you add all your fingerprints to the trust manager by default, the problem will mostly become moot, however. Otherwise, one might document `addTrustedFingerprint` API, so that applications can load fingerprints from properties files, or however they like and pass it to the trust managed using a documented API.

**Comment by berend** [comment]
We will discuss this and I will come back to you on this.

**Pull request closed without merging**
